### ISSUE TITLE
[Bug] ImportError when importing tissue forge

### ISSUE THREAD

**Issue by JulianoGianlupi** [tissue-forge/tissue-forge#4]
Clean install of TF in fresh conda environment (only TF and its dependencies installed), when trying to import tissue forge I get an import error.

Example

```
(tf) D:\modeling\PhenoCellPy\TF_examples>python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tissue_forge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Anaconda3\envs\tf\lib\site-packages\tissue_forge\__init__.py", line 21, in <module>
    from .tissue_forge import *
  File "d:\Anaconda3\envs\tf\lib\site-packages\tissue_forge\tissue_forge.py", line 13, in <module>
    from . import _tissue_forge
ImportError: DLL load failed while importing _tissue_forge: The specified module could not be found.
>>>
```

**Comment by JulianoGianlupi** [comment]
It was some installation error, a re-install fixed it
